# -*- coding: utf-8 -*-
"""RandomForestClassifier_in_lung cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BX4IZTvd2ZYw1Ytw_isCj80gdw1zDPcq
"""

import pandas as pd
import numpy as np
import seaborn as sns

data=pd.read_csv('/content/survey lung cancer (1).csv')

data.head()

data.isnull().sum()

sns.boxplot(data['AGE'])



Partha2005from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['GENDER'] = le.fit_transform(data['GENDER'])

data['LUNG_CANCER']=le.fit_transform(data[['LUNG_CANCER']])

data.head()

x=data.drop('LUNG_CANCER',axis=1)
y=data['LUNG_CANCER']

from sklearn.model_selection import train_test_split

xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(random_state=40, n_jobs=-1, max_depth=5, n_estimators=10000, oob_score=True)

clf.fit(xtrain,ytrain)

ypred=clf.predict(xtest)

from sklearn.metrics import accuracy_score

accuracy_score(ytest,ypred)

